[project]
site_name = "Mon Labo"
site_url = "https://monlabo.netlify.app/"
site_description = "Documentation personnelle pour l'administration système, backups et configurations"
site_author = "David Couronne"

[project.theme]
features = [
    "navigation.footer",
    "navigation.instant",
    "navigation.top",
    "content.code.copy"
]


[[project.theme.palette]] 
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.repo]
url = "https://github.com/DavidCouronne/monlabo"
name = "DavidCouronne/monlabo"
edit_uri = "edit/main/docs/"

nav = [
  { Accueil = "index.md" },
  { Installation = [
    "installation/index.md",
    { "Outils de Base" = "installation/outils-base.md" },
    { "Project Bluefin & Chezmoi" = "installation/bluefin-chezmoi.md" },
    { "Montage NAS" = "installation/montage-nas.md" },
  ]},
  { Backup = [
    "backup/index.md",
    { "Backup Immich" = "backup/immich.md" },
    { "Backup Jellyfin" = "backup/jellyfin.md" },
  ]},
  { Guides = [
    { "SSH" = "guides/ssh-guide.md" },
    { "Git & GitHub CLI" = "guides/git-guide.md" },
    { "LUKS + Btrfs" = "guides/luks-btrfs-montage-auto.md" },
    { "Bazzite LUKS" = "guides/bazzite-luks-bootstrap.md" },
    { "Docker sur Ubuntu" = "guides/ubuntu-docker.md" },
    { "Immich Podman" = "guides/immich-podman.md" },
    { "Jellyfin Podman" = "guides/jellyfin-podman.md" },
    { "Navidrome Podman" = "guides/navidrome-podman.md" },
    { "Backup Navidrome-Immich" = "guides/backup-navidrome-immich.md" },
  ]},
  { Minecraft = "minecraft/index.md" },
  { Zensical = [
    { "Zensical CheatSheet" = "zensical/zensical-cheatsheet.md" },
    { "Zensical Guide" = "zensical/zensical-guide.md" },
  ]}

]

[project.markdown_extensions]
admonition = {}
"pymdownx.details" = {}
"pymdownx.superfences" = {}
"pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
"pymdownx.tabbed" = { alternate_style = true, combine_header_slug = true }
attr_list = {}
md_in_html = {}
def_list = {}
footnotes = {}
"pymdownx.critic" = {}
"pymdownx.caret" = {}
"pymdownx.mark" = {}
"pymdownx.tilde" = {}
"pymdownx.keys" = {}
"pymdownx.tasklist" = { custom_checkbox = true, clickable_checkbox = true }
"pymdownx.smartsymbols" = {}
"pymdownx.betterem" = { smart_enable = "all" }
tables = {}
abbr = {}

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
